"""Fase 1 y 2: Arquitectura multiempresa

Revision ID: 0c2117f288e6
Revises: 67ab697473b2
Create Date: 2026-07-23 10:06:57.983008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2117f288e6'
down_revision = '67ab697473b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_categorias_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key('fk_categorias_empresa_id', 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True))
        batch_op.drop_column('email_contacto')
        batch_op.drop_column('activa')

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_movimientos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key('fk_movimientos_empresa_id', 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_productos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key('fk_productos_empresa_id', 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subcategorias_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key('fk_subcategorias_empresa_id', 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_foreign_key('fk_usuarios_empresa_id', 'empresas', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_subcategorias_empresa_id'))
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_productos_empresa_id'))
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_movimientos_empresa_id'))
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activa', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_contacto', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('fecha_vencimiento')
        batch_op.drop_column('estado')
        batch_op.drop_column('plan')
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')
        batch_op.drop_column('email')
        batch_op.drop_column('nombre')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_categorias_empresa_id'))
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###
