"""Composite unique constraints for multi-tenant scaling

Revision ID: 3d8b09788764
Revises: 4be90d843fb9
Create Date: 2026-07-23 11:58:31.133412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8b09788764'
down_revision = '4be90d843fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_categoria_nombre_empresa', ['nombre', 'empresa_id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_codigo'))
        batch_op.create_index(batch_op.f('ix_productos_codigo'), ['codigo'], unique=False)
        batch_op.drop_index(batch_op.f('ix_productos_codigo_barras'))
        batch_op.create_index(batch_op.f('ix_productos_codigo_barras'), ['codigo_barras'], unique=False)
        batch_op.create_unique_constraint('uix_producto_codigo_barras_empresa', ['codigo_barras', 'empresa_id'])
        batch_op.create_unique_constraint('uix_producto_codigo_empresa', ['codigo', 'empresa_id'])

    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uix_subcat_nombre_categoria'), type_='unique')
        batch_op.create_unique_constraint('uix_subcat_nombre_categoria_empresa', ['nombre', 'categoria_id', 'empresa_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategorias', schema=None) as batch_op:
        batch_op.drop_constraint('uix_subcat_nombre_categoria_empresa', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_subcat_nombre_categoria'), ['nombre', 'categoria_id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('uix_producto_codigo_empresa', type_='unique')
        batch_op.drop_constraint('uix_producto_codigo_barras_empresa', type_='unique')
        batch_op.drop_index(batch_op.f('ix_productos_codigo_barras'))
        batch_op.create_index(batch_op.f('ix_productos_codigo_barras'), ['codigo_barras'], unique=1)
        batch_op.drop_index(batch_op.f('ix_productos_codigo'))
        batch_op.create_index(batch_op.f('ix_productos_codigo'), ['codigo'], unique=1)

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint('uix_categoria_nombre_empresa', type_='unique')

    # ### end Alembic commands ###
