"""Add payment fields to Empresa

Revision ID: 4be90d843fb9
Revises: ed4181d061fc
Create Date: 2026-07-23 11:53:24.569791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be90d843fb9'
down_revision = 'ed4181d061fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mp_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mp_preapproval_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('mp_preapproval_id')
        batch_op.drop_column('mp_customer_id')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('payment_provider')

    # ### end Alembic commands ###
