"""Fase 5: Roles y Permisos

Revision ID: b5ea50f69eb1
Revises: 0c2117f288e6
Create Date: 2026-07-23 10:28:10.527028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ea50f69eb1'
down_revision = '0c2117f288e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=50), nullable=True))

    # Data migration: Set role based on es_admin
    op.execute("UPDATE usuarios SET rol = 'Administrador' WHERE es_admin = 1")
    op.execute("UPDATE usuarios SET rol = 'Operador' WHERE es_admin = 0")

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('es_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
