"""Fase 6: Add ultimo_login

Revision ID: e36e23d3c202
Revises: b5ea50f69eb1
Create Date: 2026-07-23 11:24:41.619732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36e23d3c202'
down_revision = 'b5ea50f69eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ultimo_login')

    # ### end Alembic commands ###
