"""Add auditoria model

Revision ID: ed4181d061fc
Revises: e36e23d3c202
Create Date: 2026-07-23 11:45:26.639977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4181d061fc'
down_revision = 'e36e23d3c202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.String(length=50), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditorias_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditorias_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditorias_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditorias_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_auditorias_fecha'))
        batch_op.drop_index(batch_op.f('ix_auditorias_empresa_id'))

    op.drop_table('auditorias')
    # ### end Alembic commands ###
